title:             Travel Blog 
email:             your-email@example.com
description:       A Blog About Travel
author:            Terri Marie Grierson
baseurl:           ""
url:               "https://blogaway.github.io"

# Social Profiles
twitter_username:  SBootstrap
github_username:   BlackrockDigital
facebook_username: StartBootstrap

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
